### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by leonboe1** [Infineon/TLI493D-W2BW#1]
Hi,

I tried out the Cartesian example with an ESP32 module. However, the code won't compile in Arduino IDE. 

Error message:

```
Arduino: 1.8.16 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"


/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp: In destructor 'Tli493d::~Tli493d()':
/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp:32:18: error: 'class TwoWire' has no member named 'end'
  mInterface.bus->end();
                  ^
/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp: In member function 'void Tli493d::resetSensor()':
/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp:478:18: error: 'class TwoWire' has no member named 'end'
  mInterface.bus->end();
                  ^
exit status 1
Error compiling for board ESP32 Dev Module.
```

I tried to remove the calls to "end" in the cpp file. The code compiled, however, the sensor values always stayed the same even though I brought a magnet close to the sensor.

Maybe its possible to change the library so it works for ESP32 as well?

Thanks, Leon

**Comment by 9Volts9er** [comment]
Hi,
which arduino-esp32 version do you have? There are actually two links for the Boards-Manager-URL around in the internet:
- [https://dl.espressif.com/dl/package_esp32_index.json](https://dl.espressif.com/dl/package_esp32_index.json)
- [https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json](https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json)

Espressif seems to have switched over to Github for hosting their Arduino implementation.
You can refer to this guide to make sure, you have the newest version installed: [https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)

Currently I cannot test this on a real ESP32, but at least, it immediately compiled without errors and without the need to make any changes to the TLI493D-W2BW library.

However, in the ESP32s Wire.h you can find the following comment:
```
    //call setPins() first, so that begin() can be called without arguments from libraries
    bool setPins(int sda, int scl);
```

This means, the Cartesian example of the TLI493D-W2BW will not work as it is, but you need to define your I2C pins before using the library.

Can you test if it works with those changes?

**Comment by leonboe1** [comment]
Thanks for the quick reply! I actually used an old arduino-esp32 version. The code now compiles fine, but I get the following warning:

```
/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp: In member function 'bool Tli493d::setWakeUpThreshold(float, float, float, float, float, float)':
/Users/leon/Documents/Arduino/libraries/TLI493D/src/Tli493d.cpp:263:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

Also, I have the same problem with the sensor values. They do not change:

```
15:42:48.514 -> -265.97 ; -265.97 ; -265.97
15:42:49.604 -> -265.97 ; -265.97 ; -265.97
15:42:50.703 -> -265.97 ; -265.97 ; -265.97
15:42:51.820 -> -265.97 ; -265.97 ; -265.97
```

However, the example "Raw_I2C_readout" works fine.

Do you have an idea why this might be happening?

My code: 

```

#include <Tli493d.h>
#include <Wire.h>       // default I²C library

//Voltage level LOW at pin 5 switches on the sensor VDD
Tli493d Tli493dMagnetic3DSensor = Tli493d(5,LOW);

void setup() {

  Serial.begin(9600);
  Wire.begin();

  Tli493dMagnetic3DSensor.begin();
}

void loop() {
  Tli493dMagnetic3DSensor.updateData();

  Serial.print(Tli493dMagnetic3DSensor.getX());
  Serial.print(" ; ");
  Serial.print(Tli493dMagnetic3DSensor.getY());
  Serial.print(" ; ");
  Serial.print(Tli493dMagnetic3DSensor.getZ());
  Serial.println("");
  delay(100);
}
```

Greetings,
Leon

**Comment by 9Volts9er** [comment]
Ah yes, I see. The function `setWakeUpThreshold()` misses a `return ret;` at the end, but this error is not critical.

You probably do not need the `Wire.begin();` as it is called within the `Tli493dMagnetic3DSensor.begin()`.
If no I2C pins are defined, then the `Wire.begin()` uses standard pins, which are probably defined in the "pins_arduino.h". So you can ignore my previous comment about the function `setPins(int sda, int scl);`. At least, if you are using this standard I2C pins from your board, but this seems to be the case, when the raw readout example works.

Ok, coming to the issue with only reading -265.97: This usually means, that the sensor is not responding, so either it is not supplied with power or it is wrongly configured. I would guess, that it is the first case.
The example code assumes, you are using the Infineon TLI493D-W2BW Shield2Go hardware. This connects the sensors VDD to 3V3 via a MOSFET, which is controlled by a microcontroller pin. In case of the XMC2Go this power control pin is pin 5, and as soon as this pin switches to LOW, the sensor is supplied with 3V3.
`Tli493d Tli493dMagnetic3DSensor = Tli493d(5,LOW);`
This line assinges the power pin to 5, and the sensor active level to LOW.

Do you have a similar setup? Or do you have the sensors VDD directly connected to pin 5 of your ESP32? 
Then you would need to change the "LOW" to "HIGH".

Or is a SDA or SCL maybe connected to pin 5 of your ESP32? Then configuring it as power pin may conflict with the communication.
Can you check this?

**Comment by leonboe1** [comment]
Thanks a lot! It works now in Arduino IDE! FYI: I connected the sensor directly to VDD and GND pins of my ESP32. Removing the power pin from the constructor did the trick (`Tli493d();`). 

However, the project the library should be integrated in is managed by PlatformIO, which unfortunately uses an older version of arduino-esp32. I tried to update the version of arduino-esp32, but then some issues with other libraries occurred.

So I forked the library and made two changes:

- reordered `AccessMode_e` and `TypeAddress_e` in the header file (compiler error, `[-Werror=reorder]`)
- removed calls to `mInterface.bus->end();` which are not supported by the older version of arduino-esp32

It seems to work.

Leon

**Comment by 9Volts9er** [comment]
Great to hear that it works.
I will close the Issue then, but feel free to reopen it, when any further problems occur.

**Comment by leonboe1** [comment]
Hi,

unfortunately, another problem occurred and I was unable to fix it. Maybe you have an idea why it happens. This is my code:

```
Tli493d Tli493dMagnetic3DSensor = Tli493d();

...

void setupHall()
{
    Tli493dMagnetic3DSensor.begin();

    Tli493dMagnetic3DSensor.disableTemp();
    Tli493dMagnetic3DSensor.disableWakeUp();
    Tli493dMagnetic3DSensor.disableBz();
    Tli493dMagnetic3DSensor.disableInterrupt();
    Tli493dMagnetic3DSensor.setMeasurementRange(Tli493dMagnetic3DSensor.EXTRASHORT);

}

float getAngle()
{
  Tli493dMagnetic3DSensor.begin();
  Tli493dMagnetic3DSensor.updateData();

  float x = Tli493dMagnetic3DSensor.getX();
  float y = Tli493dMagnetic3DSensor.getY();

  …
}
```

I am still using the ESP32-CAM and don't use the interrupt port. Also, I still didn't set a power port - instead, I connected the sensor directly to GND and 3v3 of the board and left the constructor arguments blank.

I noticed that if the camera of the board is activated, the sensor "freezes" (just like in my second post). The camera is connected with I2C as well, so I thought that both devices might interfere with each other. I made sure that the camera and the sensor readout cannot occur at the same time. However, that didn't fix the problem. After some investigation I noticed that if I run `Tli493dMagnetic3DSensor.begin()` before refreshing new data with `Tli493dMagnetic3DSensor.updateData()`, this problem won't happen. I wasn't sure why, though.

However, I noticed that sometimes (not very often and not reproducible) the freeze would reoccur even with the applied solution above. Other sensors connected via I2C worked fine. Do you have an idea why? In the library documentation was something about "Collision Avoidance and Clock Stretching", but I didn't quite understand what is meant by that. Does this maybe have something to do with it?

Best wishes,
Leon

**Comment by 9Volts9er** [comment]
Hi,
for a detailed description of Collision Avoidance and Clock Stretching, you can refer to the [User Manual](https://www.infineon.com/dgdl/Infineon-TLI_493D-W2BW-UserManual-v01_10-EN.pdf?fileId=5546d46273a5366f0173be229e1b1512).

Collision Avoidance (CA) goes along with the Interrupt (INT) of the sensor. But here this depends a little bit on your Hardware-Setup. The TLI493D-W2BW has two separated pins for SCL and INT. They may be connected together, then the following settings for INT and CA can be made:

- INT enabled, CA enabled -> The Interrupt pulse will not be transmitted during an active communication. But the microcontroller might not be able to handle an interrupt pulse on the same line as SCL is.
- INT disabled, CA enabled -> Clock stretching is active. This means, when the microcontroller requests data, the sensor will hold the SCL line LOW ("stretching the clock") until it is done with the AD-conversion. That makes sure, you will not get corrupted data, if the sensor overwrites data during readout.
- INT enabled, CA disabled -> INT pulse can be sent while there is an ongoing communication on the I2C lines. This will corrupt the communication.
- INT disabled, CA disabled -> Clock stretching is inactive, so the sensor might overwrite data while it is read, which will lead to corrupted data. But this can be checked if reading the Diag-register (0x06) as well and checking the framecounter bits. Or by using the Master controlled mode to have the full control of when the sensor is measuring.

However, if you have two separate lines for SCL and INT, you have the following options:

- INT enabled, CA enabled -> The Interrupt pulse will not be sent during an active communication. But as the INT line is separate, this does not make very much sense.
- INT disabled, CA enabled -> Clock stretching is not available as it uses the INT line, so this option does not make very much sense either.
- INT enabled, CA disabled -> INT pulse can be sent during an ongoing I2C communication. No problem here as it is on a separate line.
- INT disabled, CA disabled -> Same situation as for shorted SCL/INT-lines.

So it depends on your hardware setup, which option is best for you. But I'm not sure, if this solves your problem.
Maybe you can simply try it again with the best suited option from above.
And if this does not help: Can you have a look with an oscilloscope on the I2C lines? Maybe you can capture the moment when the sensor freezes, so we can analyze what's going on.

**Comment by leonboe1** [comment]
Hi, thank you for your detailed explanation! I checked my code again and ran the library on Core1 instead of Core0 of my board. Since then, I didn't have any issues. Maybe this fixed the problem. Fingers crossed...
